---
title: "README"
author: "Alejandro Borges"
date: "5/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting and cleaning data 
### Course Project


####Instructions:
1.- setwd(to the directory where you cloned this repo)

Download file at https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip and unzip it in this directory. It should create a subdirectory "UCI HAR Dataset".

2.- Run the run_analysis.R script either directly with R or using:
source('./run_analysis.R')

Its quite chatty and can take a little while, but if you scroll up when it finishes, you will see it executes each requirement for the course in order, print()ing helpful comments as to what it was doing at the time it was running.

The resulting dataset is in the by_activity_and_subject.csv file.

####Codebook:
The codebook.txt file contains the description of the resulting dataset.

####Analysis:

At first, mostly bash was what was needed to check for the main things:
```{bash}
ls -l "./UCI HAR Dataset/test"
```
```{bash}
wc -l "./UCI HAR Dataset/test/X_test.txt" "./UCI HAR Dataset/train/X_train.txt"
```
So about 30 to 70 percent in each file, as expected. 
But how are things ordered? 
```{bash}
head -n 1 "./UCI HAR Dataset/test/X_test.txt" | wc -w
```
Ah... each line, a vector of 561 variables. That is what the documentation of the dataset says.

If this is true, then the subject file and the y_test files (each identifying the performing subject and the activity being performed by each observation), must also have the same length:
```{bash}
wc -l "./UCI HAR Dataset/test/y_test.txt" "./UCI HAR Dataset/test/subject_test.txt" 
```
Yes. Same number of lines in each. Does this also happen in the train directory?
```{bash}
wc -l "./UCI HAR Dataset/train/y_train.txt" "./UCI HAR Dataset/train/subject_train.txt" "./UCI HAR Dataset/train/X_train.txt"
```

It appears so! 

Ok, so we also have a file to translate activity numbers into activity names:
```{bash}
cat "./UCI HAR Dataset/activity_labels.txt"
```
Then that means activity files should have 1-6 values allways:
```{bash}
echo train
sort -u "./UCI HAR Dataset/train/y_train.txt"
echo test
sort -u "./UCI HAR Dataset/test/y_test.txt"
```
Yup. So with that info, i proceded to create the functions to load activities and subjects and then one for the full X_dirname.txt file. This last one is the most critical one and its called featureVector(dname), where dname is either "test" or "train"

All anyone would need to know about how this data was loaded and transformed is in that function.
